### ISSUE TITLE
Peer-to-peer code review (2021-10-15)

### ISSUE THREAD

**Issue by piero-vic** [nicupop729/Exhibition-Page#3]
# Hi, @nicupop729 
### Things to highlight ✨
- Your design is consistent.
- Mobile menu design it's pretty cool.

## Thigns I may change. ♻️
- You are repeating a lot of code on the two css files. You may want to try to write a main css file and use extra files for page specific styling. Link both files in the HTML when needed.
- This section is redundant. You can call `document.querySelector()` and `document.createElement()` directly. 
https://github.com/nicupop729/Exhibition-Page/blob/f8197f8ca3562638880e3ad1321a136adab70581/main.js#L1-L2

- This section it's too long and a little bit hard to read. I will consider using `innerHTML` instead of create each element individually.
https://github.com/nicupop729/Exhibition-Page/blob/f8197f8ca3562638880e3ad1321a136adab70581/main.js#L4-L36

- You have the node_modules folder on the repo. Please consider deleting it.

**Comment by nicupop729** [comment]
closed
